import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {Col, Menu, MenuProps, Row} from "antd";
import Link from "next/link";


export default function Home() {
    const items: MenuProps['items']=[
        {
            label:<Link href={`/`}>首页</Link>,
            key:"home"
        }
    ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Row gutter={16}>
          <Col span={4}>
            <img src={`https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg`}/>
          </Col>
          <Col span={20}>
              <Menu
                  mode={"horizontal"}
                items={items}
              />
          </Col>
        </Row>
      </main>
    </>
  )
}
